/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.impresion;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JPanel;

/**
 *
 * @author pablo
 */
public class InterfazImpresion extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form InterfazImpresion
     */
    public InterfazImpresion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Impresion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Impresion.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ImpresionLayout = new javax.swing.GroupLayout(Impresion);
        Impresion.setLayout(ImpresionLayout);
        ImpresionLayout.setHorizontalGroup(
            ImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );
        ImpresionLayout.setVerticalGroup(
            ImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Impresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(571, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(231, 231, 231))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Impresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //jPanel1.printAll(getGraphics());
            PrinterJob g = PrinterJob.getPrinterJob();
            g.setPrintable(this);
            boolean top = g.printDialog();
            if (top) {
                g.print();
            }

        } catch (HeadlessException | PrinterException e) {
            System.out.println("Error al Imprimir" + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazImpresion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Impresion;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    public JPanel getImpresion() {
        return Impresion;
    }

    public void setImpresion(JPanel Impresion) {
        Impresion.setSize(this.Impresion.getWidth(),this.Impresion.getHeight());
        this.Impresion.removeAll();
        this.Impresion.add(Impresion);
        this.Impresion.revalidate();
    }

    

    

    public void Imprimir(JPanel panelImpresora) {
        
        mandarImprimir();
    }

    public void mandarImprimir() {
        try {
            //jPanel1.printAll(getGraphics());
            PrinterJob g = PrinterJob.getPrinterJob();
            g.setPrintable(this);
            boolean top = g.printDialog();
            if (top) {
                g.print();
            }

        } catch (HeadlessException | PrinterException e) {
            System.out.println("Error al Imprimir" + e.getMessage());
        }
    }

    @Override
    public int print(Graphics graf, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if (pageIndex > 0) {
            System.out.println("asd");
            return NO_SUCH_PAGE;
        }
        Graphics2D a = (Graphics2D) graf;
        a.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
        //a.scale(1.0, 1.1);
        Impresion.printAll(graf);
        System.out.println("kjhj");
        return PAGE_EXISTS;
    }
}
