/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.impresion;


/**
 *
 * @author pablo
 */
public class otros extends javax.swing.JPanel {

    /**
     * Creates new form impresora
     */
    public otros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelCarnet = new javax.swing.JLabel();
        labelNroOrden = new javax.swing.JLabel();
        labelCelular = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTrabajo = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelRegistro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelEntrega = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRepuesto = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        labelNombre1 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        labelDireccion1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labelCarnet1 = new javax.swing.JLabel();
        labelNroOrden1 = new javax.swing.JLabel();
        labelCelular1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTrabajo1 = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        labelRegistro1 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        labelEntrega1 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtRepuesto1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtServicio1 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(521, 792));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(766, 437));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Dialog", 2, 8)); // NOI18N
        jLabel11.setText("64-66285");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 90, -1));

        labelNombre.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        labelNombre.setText("Pablo Segovia Vargas");
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 140, -1));

        jLabel48.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel48.setText("Recibí Conforme");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        labelDireccion.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        labelDireccion.setText("Av Japon 93");
        jPanel1.add(labelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("N° Orden");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        labelCarnet.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        labelCarnet.setText("12345678");
        jPanel1.add(labelCarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 100, -1));

        labelNroOrden.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelNroOrden.setText("0001");
        jPanel1.add(labelNroOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 64, -1));

        labelCelular.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        labelCelular.setText("78670128");
        jPanel1.add(labelCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 100, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel14.setText("Fecha Recepción");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("SOPORTE TÉCNICO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, 10));

        jLabel49.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel49.setText("Costo");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("OTROS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, 20));

        jLabel50.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel50.setText("BS.");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        jLabel51.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel51.setText("Costo");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("aakar", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("A.M.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 38));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Comerzializadores");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, -1));

        jLabel52.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel52.setText("Servicio");
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        jLabel43.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 0, 0));
        jLabel43.setText("\"Señor cliente si en el plazo de 30 dias no recoge su equipo la empresa no se hace responsable\"");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel15.setText("Fecha Entrega Apróximada");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jLabel44.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel44.setText("TRABAJO A REALIZAR");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel53.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel53.setText("CI:_______________");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 2, 8)); // NOI18N
        jLabel7.setText("Raul Otero #101");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel16.setText("año/mes/dia");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        txtTrabajo.setColumns(20);
        txtTrabajo.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        txtTrabajo.setRows(5);
        txtTrabajo.setText("\n\n\n\n\n\n\n\nOBSERVACIONES: ");
        jScrollPane1.setViewportView(txtTrabajo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 470, 120));

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel17.setText("año/mes/dia");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel18.setText("Hora");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 2, 8)); // NOI18N
        jLabel8.setText("Cel:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 30, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel19.setText("Hora");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 2, 8)); // NOI18N
        jLabel9.setText("71164598 - 73417476");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 110, -1));

        labelRegistro.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        labelRegistro.setText("05/06/2019");
        jPanel1.add(labelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("TODA  ENTREGA  CON  ESTA  BOLETA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        labelEntrega.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        labelEntrega.setText("05/06/2019");
        jPanel1.add(labelEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 140, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel24.setText("DATOS  DEL  CLIENTE");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("o CON  CARNET  DE  IDENTIDAD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        txtRepuesto.setText("1000");
        jPanel1.add(txtRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 50, 20));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel25.setText("Nombre:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        txtServicio.setText("1000");
        jPanel1.add(txtServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 50, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel26.setText("CI:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 40, -1));

        jLabel103.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel103.setText("Repuesto");
        jPanel1.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 2, 8)); // NOI18N
        jLabel10.setText("Tel:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 20, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel27.setText("Dirección:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel104.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel104.setText("BS.");
        jPanel1.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        jLabel47.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel47.setText("TECNICO");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel28.setText("Celular:");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(766, 437));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Dialog", 2, 8)); // NOI18N
        jLabel13.setText("64-66285");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 90, -1));

        labelNombre1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        labelNombre1.setText("Pablo Segovia Vargas");
        jPanel2.add(labelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 140, -1));

        jLabel54.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel54.setText("Recibí Conforme");
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        labelDireccion1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        labelDireccion1.setText("Av Japon 93");
        jPanel2.add(labelDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("N° Orden");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        labelCarnet1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        labelCarnet1.setText("12345678");
        jPanel2.add(labelCarnet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 100, -1));

        labelNroOrden1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelNroOrden1.setText("0001");
        jPanel2.add(labelNroOrden1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 64, -1));

        labelCelular1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        labelCelular1.setText("78670128");
        jPanel2.add(labelCelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 100, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel21.setText("Fecha Recepción");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setText("SOPORTE TÉCNICO");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, 10));

        jLabel55.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel55.setText("Costo");
        jPanel2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setText("OTROS");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, 20));

        jLabel56.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel56.setText("BS.");
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        jLabel57.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel57.setText("Costo");
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        jLabel29.setFont(new java.awt.Font("aakar", 1, 30)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 153));
        jLabel29.setText("A.M.");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 38));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 102));
        jLabel30.setText("Comerzializadores");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, -1));

        jLabel58.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel58.setText("Servicio");
        jPanel2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        jLabel45.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 0, 0));
        jLabel45.setText("\"Señor cliente si en el plazo de 30 dias no recoge su equipo la empresa no se hace responsable\"");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel31.setText("Fecha Entrega Apróximada");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jLabel46.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel46.setText("TRABAJO A REALIZAR");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel59.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel59.setText("CI:_______________");
        jPanel2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jLabel32.setFont(new java.awt.Font("Dialog", 2, 8)); // NOI18N
        jLabel32.setText("Raul Otero #101");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, -1));

        jLabel33.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel33.setText("año/mes/dia");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        txtTrabajo1.setColumns(20);
        txtTrabajo1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        txtTrabajo1.setRows(5);
        txtTrabajo1.setText("\n\n\n\n\n\n\n\nOBSERVACIONES: ");
        jScrollPane2.setViewportView(txtTrabajo1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 470, 120));

        jLabel34.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel34.setText("año/mes/dia");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel35.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel35.setText("Hora");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel36.setFont(new java.awt.Font("Dialog", 2, 8)); // NOI18N
        jLabel36.setText("Cel:");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 30, -1));

        jLabel37.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel37.setText("Hora");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel38.setFont(new java.awt.Font("Dialog", 2, 8)); // NOI18N
        jLabel38.setText("71164598 - 73417476");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 110, -1));

        labelRegistro1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        labelRegistro1.setText("05/06/2019");
        jPanel2.add(labelRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, -1));

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 0, 0));
        jLabel39.setText("TODA  ENTREGA  CON  ESTA  BOLETA");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        labelEntrega1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        labelEntrega1.setText("05/06/2019");
        jPanel2.add(labelEntrega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 140, -1));

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel40.setText("DATOS  DEL  CLIENTE");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 0, 0));
        jLabel41.setText("o CON  CARNET  DE  IDENTIDAD");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        txtRepuesto1.setText("1000");
        jPanel2.add(txtRepuesto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 50, 20));

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel42.setText("Nombre:");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        txtServicio1.setText("1000");
        jPanel2.add(txtServicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 50, -1));

        jLabel60.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel60.setText("CI:");
        jPanel2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 40, -1));

        jLabel105.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel105.setText("Repuesto");
        jPanel2.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        jLabel61.setFont(new java.awt.Font("Dialog", 2, 8)); // NOI18N
        jLabel61.setText("Tel:");
        jPanel2.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 20, -1));

        jLabel62.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel62.setText("Dirección:");
        jPanel2.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel106.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel106.setText("BS.");
        jPanel2.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        jLabel63.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel63.setText("TECNICO");
        jPanel2.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel64.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel64.setText("Celular:");
        jPanel2.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCarnet;
    private javax.swing.JLabel labelCarnet1;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelCelular1;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelDireccion1;
    private javax.swing.JLabel labelEntrega;
    private javax.swing.JLabel labelEntrega1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelNroOrden;
    private javax.swing.JLabel labelNroOrden1;
    private javax.swing.JLabel labelRegistro;
    private javax.swing.JLabel labelRegistro1;
    private javax.swing.JTextField txtRepuesto;
    private javax.swing.JTextField txtRepuesto1;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtServicio1;
    private javax.swing.JTextArea txtTrabajo;
    private javax.swing.JTextArea txtTrabajo1;
    // End of variables declaration//GEN-END:variables

     public void fillForm(String id ,String fecha_recepcion,String fecha_entrega,
                        String repuesto,String Servicio,
                       String carnet,String nombre, String telefono,String direccion,String descripcion
                       ){
      
      if(Integer.parseInt(id)<10){
          id="000"+id;
      }
      if(Integer.parseInt(id)>=10 && Integer.parseInt(id)<100){
          id="00"+id;
      }
      if(Integer.parseInt(id)>=100 && Integer.parseInt(id)<1000){
          id="0"+id;
      }
      this.labelNroOrden.setText(id);
      this.labelNroOrden1.setText(id);
      
      this.labelRegistro.setText(fecha_recepcion);
      this.labelRegistro1.setText(fecha_recepcion);
      
      this.labelEntrega.setText(fecha_entrega);
      this.labelEntrega1.setText(fecha_entrega);
      
      this.labelCarnet.setText(carnet);
      this.labelCarnet1.setText(carnet);
      
      this.labelNombre.setText(nombre);
      this.labelNombre1.setText(nombre);
      
      this.labelCelular.setText(telefono);
      this.labelCelular1.setText(telefono);
      
      this.labelDireccion.setText(direccion);
      this.labelDireccion1.setText(direccion);
      
      
      
      this.txtTrabajo.setText(descripcion);
      this.txtTrabajo1.setText(descripcion);
      
      this.txtServicio.setText(Servicio);
      this.txtServicio1.setText(Servicio);
      
      this.txtRepuesto.setText(repuesto);
      this.txtRepuesto1.setText(repuesto);
      
  }
}
